### ISSUE TITLE
Добавить возможность менять очередность тестов или объединять их в группы

### ISSUE THREAD

**Issue by Nrj-ex** [TestMace/TestMace-issues#14]
Сейчас это возможно сделать только перемещением из одной папки в другую.
Ещё можно сделать возможность составления тестовых сценариев из нескольких запросов.

**Comment by Ratuvog** [comment]
One of the main concepts of the product is Don't Repeat Yourself, which implies the ability to create a node, test, script once and reuse it without the need to create the same nodes. Using the Link node, you can reuse previously created nodes and scripts with the ability to parameterize their execution. Starting with version 1.0.0, it is now possible to reuse Assertion nodes.
The execution order of Link and Link Assertion clearly corresponds to their location in the project.
