### ISSUE TITLE
Динамические параметры видны только в родительском запросе

### ISSUE THREAD

**Issue by Nrj-ex** [TestMace/TestMace-issues#15]
Нет возможности посмотреть все динамические параметры доступные в какой либо папке.
http://i.imgur.com/AdbzeQe.png
Их вообще можно посмотреть только там где они были созданы.
Возможно иметь весь список доступных параметров(не только динамических) в одном месте так же было бы хорошей идеей (с поиском по ним).

**Comment by Ratuvog** [comment]
We have released this feature in 1.0.0. You can see all dynamic variable values which assigned to the node in "Variables -> Values" tab.
