### ISSUE TITLE
Incorrect headers import from cURL when header name is not specified

### ISSUE THREAD

**Issue by kotokur** [TestMace/TestMace-issues#17]
For now request:

curl -d 'client_id=4' -H "application/x-www-form-urlencoded" -X POST https://testmace-stage.herokuapp.com/posts

must be explicitly converted to:

curl -d 'client_id=4' -H "Content-Type: application/x-www-form-urlencoded" -X POST https://testmace-stage.herokuapp.com/posts

Expected behavior:

Request  "curl -d 'client_id=4' -H "application/x-www-form-urlencoded" -X POST https://testmace-stage.herokuapp.com/posts" imports correctly

**Comment by dima11221122** [comment]
Apparently, such headers are incorrect and should be ignored
