### ISSUE TITLE
Chat to send issues in the app doesn't show

### ISSUE THREAD

**Issue by stokescomp** [TestMace/TestMace-issues#34]
I saw a chat feature to report bugs in the app. 
If worked the first time I started the TestMace app. Then after closing the app and reopening it doesn't show the chat anymore.
I see there is a menu option at view -> toggle chat.
I click it and nothing happens. I see in dev tools it says this in the console:
close-transaction: 8.702880859375ms

**Comment by dima11221122** [comment]
Hello, thank you for your report. Could you say your OS?

**Comment by stokescomp** [comment]
Windows 10 enterprise 1903.

**Comment by stokescomp** [comment]
And I tried it today and the chap opens everytime I open the program. Maybe there was a network issue connecting to the chat program yesterday when it didn't load.

**Comment by stokescomp** [comment]
I will close this issue as I can't reproduce it anymore.

**Comment by dima11221122** [comment]
It might be a temporary problem. Anyway if you can reproduce the bug feel free to open it.)
