### ISSUE TITLE
Поломалось наследование переменных от предков

### ISSUE THREAD

**Issue by ValeriyGourov** [TestMace/TestMace-issues#38]
После обновления на версию 0.0.1-beta.29 поломалось наследование переменных от предков. Например, в проекте есть такая структура папок:
- API
  - v1

В переменных окружения создана переменная:
`Host: http://localhost:59127`

Для папки _API_ создана переменная:
`AddressPrefix: ${$env.Host}/api`

В папке _v1_ создаю переменную:
`AddressPrefixV1: ${$parent.AddressPrefix}/v1`

Предполагается, что значение `$parent.AddressPrefix` будет равно `http://localhost:59127/api`, однако когда я навожу курсор на это выражение, то во всплывающей подсказке вижу только `http://localhost:59127`. Соответственно это же значение уходит дальше по иерархии и используется в запросах, что не соответствует ожидаемому поведения. А значит пользоваться запросами, в которых используются такие переменные, становится просто невозможно. До обновления на указанную версию всё работало корректно.

**Comment by dima11221122** [comment]
Здравствуйте. Да, судя по всему есть проблема. Постараемся поправить прям в ближайшее время

**Comment by dima11221122** [comment]
Поправили в версии 0.0.1-beta.30

**Comment by ValeriyGourov** [comment]
Всё работает. Спасибо.
