### ISSUE TITLE
Testmace cli: provide option to specify report output file

### ISSUE THREAD

**Issue by LennyPenny** [TestMace/TestMace-issues#43]
Would be awesome if you added an `-o` (or similar) parameter to specify the output path/file for the generated report. 
We require this feature to make proper use of this in a CI pipeline (currently working around this missing feature with a cd hack that is susceptible to race conditions)

**Comment by Nerzal** [comment]
Sounds like a fantastic idea :thinking: :) :-* <3

**Comment by benbarten** [comment]
Love it!

**Comment by dima11221122** [comment]
Wow, so hot feature!:) we are preparing a big update for TestMace and we'll add this feature.

**Comment by Nerzal** [comment]
@dima11221122 wanna marry me? :D

**Comment by dima11221122** [comment]
@Nerzal I think, my wife won't approve it :)

**Comment by LennyPenny** [comment]
@dima11221122 any update on this?:)

**Comment by dima11221122** [comment]
> @dima11221122 any update on this?:)

Hello, @LennyPenny . We've just released the new version of cli which support two options for junit reporter:
```
-o, --output [path]              Path to output report directory
-n --report-name [name]          Report filename
```

For example:

```
testmace-cli --reporter junit --report-name cool-report-project.xml --output /home/user /home/user/.config/testmace-config/tmp-project/Project
```
