### ISSUE TITLE
Microsoft Defender SmartScreen is detecting TestMace.exe as unsafe

### ISSUE THREAD

**Issue by mkalakota** [TestMace/TestMace-issues#47]
Hi,

After downloading `TestMace.exe` in Microsoft Edge (Chromium), Microsoft Defender SmartScreen reports App is not signed and is unsafe to install.

![image](https://user-images.githubusercontent.com/2869489/85014689-59495900-b184-11ea-9a76-d6b1424f246c.png)

Our corporate policies do not recommend using unsafe apps.

**Comment by dima11221122** [comment]
It might be because we updated the signing key for windows executables. We've already run into with such a problem and this notification will disappear for a while.
