### ISSUE TITLE
We can't download it for windows?

### ISSUE THREAD

**Issue by siamahnaf** [TestMace/TestMace-issues#58]
When we try to download it it gives this error-
![Screenshot_2022-10-26-23-48-05-80_df198e732186825c8df26e3c5a10d7cd](https://user-images.githubusercontent.com/78312010/198100071-484382d6-d7a3-40e8-a05a-a3086871f56e.jpg)

**Comment by Murtaza-arif** [comment]
Same issue

**Comment by dima11221122** [comment]
Hi, guys. @Murtaza-arif  @siamahnaf198 now it's working. Sorry for delay
