### ISSUE TITLE
Import curl request

### ISSUE THREAD

**Issue by dima11221122** [TestMace/TestMace-issues#9]

**Comment by Booggmz** [comment]
Кейс следующий: При отладке ajax запросов на сайтах, google chrome любезно предлагает скопипастить весь запрос с параметрами в качестве CURL запроса. Было бы круто, чтоб полноценный curl запрос конвертился в реквест)

![curl](https://user-images.githubusercontent.com/1027281/52621597-c5dd8500-2eb8-11e9-9f97-dc51fe1f8ca6.png)
